// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirstDemo.Models;

public partial class TableEmployee
{
    public int Id { get; set; }

    public int DepartmentId { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public DateTime BirthDay { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime ModifiedOn { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }
}