// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirstDemo.Models;

public partial class TableVisitor
{
    public int Id { get; set; }

    public int VistorTypeId { get; set; }

    public int StoreId { get; set; }

    public string FullName { get; set; }

    public string Idcard { get; set; }

    public DateTime? BirthDay { get; set; }

    public int? Gender { get; set; }

    public string PhoneNumber { get; set; }

    public string Contact { get; set; }

    public string Note { get; set; }

    public string ImageName { get; set; }

    public int NumberOfCard { get; set; }

    public bool IsApproved { get; set; }

    public DateTime? StartBorrowTime { get; set; }

    public DateTime? FinishBorrowTime { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime ModifiedOn { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }
}