// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirstDemo.Models;

public partial class TableRole
{
    public int Id { get; set; }

    public string NameEn { get; set; }

    public string NameVn { get; set; }

    public string DescriptionEn { get; set; }

    public string DescriptionVn { get; set; }

    public int Point { get; set; }
}